# Generated by Django 3.1.2 on 2021-03-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('url', models.TextField()),
                ('status', models.IntegerField(default=200)),
                ('frequency', models.IntegerField(default=600)),
            ],
        ),
        migrations.CreateModel(
            name='PageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField()),
                ('status', models.IntegerField(default=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmonit.page')),
            ],
        ),
    ]
