# Generated by Django 3.1.7 on 2021-03-21 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmonit', '0003_auto_20210321_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='frequency',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagelog',
            name='check_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
